version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.13.3-management-alpine
    hostname: rabbitmq
    restart: always
    ports:
      - "5678:5672"
      - "15678:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=jamie
      - RABBITMQ_DEFAULT_PASS=testpassword
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia/
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - coolify
    healthcheck:
      test: 'rabbitmq-diagnostics -q ping'
      interval: 30s
      timeout: 30s
      retries: 3      
      # - ./conf/:/etc/rabbitmq/
    # command: bash -c "sleep 10; rabbitmq-server;"

volumes:
  rabbitmq_data:
    #external: true
    #driver: local

networks:
  coolify: